FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Copy the dependencies file to the working directory
COPY requirements.txt .

# Install any dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Environment variables
ENV PORT_NUMBER=${PORT_NUMBER}
ENV PEERS=${PEERS}
ENV MANAGER_PORT=${MANAGER_PORT}

# Copy the content of the local src directory to the working directory
COPY . .

# Specify the command to run on container start
CMD [ "node", "./node_driver.py", "-p $PORT_NUMBER -pp $PEERS -m $MANAGER_PORT" ]